#!/usr/bin/env python3

import os
from subprocess import Popen
from urllib.parse import unquote

selected_text = os.environ.get("QUTE_SELECTED_TEXT", "")
if len(selected_text) == 0:
    exit(0)

decoded_text = unquote(selected_text)

Popen(
    [
        "python3",
        "/home/tristan/Projects/ai-asker/ask.py",
        "--gui",
        "--prompt=explain",
        decoded_text
    ]
)
