#!/usr/bin/env python3
import os

url = os.environ.get('QUTE_URL')
if url:
    new_url = url.replace('twitter.com', 'nitter.net')
    new_url = new_url.replace('youtube.com', 'yewtu.be')
    new_url = new_url.replace('medium.com', 'scribe.rip')
    new_url = new_url.replace('reddit.com', 'teddit.net')

    if new_url != url:
        with open(os.environ['QUTE_FIFO'], 'w') as fifo:
            fifo.write('open -t %s' % new_url)
