[project]
name = "voice-input"
version = "0.1.0"
description = "Real-time voice transcription system with hotkey activation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faster-whisper>=1.2.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.0",
    "black>=24.0.0",
]
