if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
PATH=$PATH:$HOME/bin
PATH=$PATH:$HOME/.local/bin

source $HOME/.zsh/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.cache/zsh/history

export DOTFILES_HOME=$HOME/Projects/dotfiles
export EDITOR=vim
export BROWSER=qutebrowser
export GPG_TTY=$(tty)
export MOZ_ENABLE_WAYLAND="1"
export QT_QPA_PLATFORM=wayland

source "$DOTFILES_HOME/zsh/keys.zsh"
source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

alias ls='lsd'
[[ -n $(diff --version | grep GNU) ]] && alias diff='diff --color'

# If windows defaults us to it's home directory, swtich to the unix one
[ $(pwd) = "/mnt/c/Users/trist" ] && cd $HOME || true

# If this is a work computer, include work specific stuff
[ -f $HOME/work.zsh ] && source $HOME/work.zsh || true

