name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and test
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: zshrc-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/zshrc-test.tar
        
    - name: Load Docker image
      run: docker load -i /tmp/zshrc-test.tar
      
    - name: Run tests
      run: make test