name: CI
# Testing Docker layer caching performance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and test
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: zshrc-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/zshrc-test.tar
        
    - name: Load Docker image
      run: docker load -i /tmp/zshrc-test.tar
      
    - name: Run tests
      run: make test

  shellcheck-ratchet:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
      
    - name: Check shellcheck ratchet
      run: |
        # Count issues in PR branch (current)
        CURRENT_COUNT=$(find . -name "*.sh" -o -path "./river/init" | grep -v ".git" | grep -v "scratch" | xargs shellcheck 2>/dev/null | wc -l)
        echo "PR branch issues: $CURRENT_COUNT"
        
        # Switch to main and count issues
        git checkout origin/main
        MAIN_COUNT=$(find . -name "*.sh" -o -path "./river/init" | grep -v ".git" | grep -v "scratch" | xargs shellcheck 2>/dev/null | wc -l)
        echo "Main branch issues: $MAIN_COUNT"
        
        # Compare and report
        if [ "$CURRENT_COUNT" -gt "$MAIN_COUNT" ]; then
          echo "❌ Shellcheck issues increased from $MAIN_COUNT to $CURRENT_COUNT"
          echo "Please fix new shellcheck issues before merging"
          exit 1
        elif [ "$CURRENT_COUNT" -lt "$MAIN_COUNT" ]; then
          echo "🎉 Shellcheck issues decreased from $MAIN_COUNT to $CURRENT_COUNT - great job!"
        else
          echo "✅ Shellcheck issues unchanged: $CURRENT_COUNT"
        fi