name: CI
# Testing Docker layer caching performance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-minimal:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and test minimal (Debian)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: zshrc-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/zshrc-test.tar
        
    - name: Load Docker image
      run: docker load -i /tmp/zshrc-test.tar
      
    - name: Run minimal tests
      run: make test

  test-maximal:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and test maximal (Arch)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.arch
        push: false
        tags: zshrc-test-arch:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/zshrc-test-arch.tar
        
    - name: Load Docker image
      run: docker load -i /tmp/zshrc-test-arch.tar
      
    - name: Run maximal tests
      run: make test-arch

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
      
    - name: Run shellcheck
      run: make shellcheck